export declare function formatTimeNumber(number: any): any;
export declare function getDay(date: any, split: any): any;
export declare function getHour(date: any): string;
export declare function dateFormater(originDate: any, isShowHour: any, opt?: any): any;
export declare function formatLyric(lyric: any): false | any[];
export declare function secondToMunite(time: any): string;
export declare function getLocationQuery(location: any): any;
export declare function pageScrollTo(height: any, offset: any): void;
export declare function loadSound(url: any): Promise<{}>;
export declare function rn(s?: number, e?: number): number;
export declare function rc(opacity: any): string;
export declare function getDOMById(id: any): HTMLElement;
export declare function downloadFile(src: any): void;
